version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

networks:
  network1:
    name: some-network
    external: true